### ISSUE TITLE
auto save feature

### ISSUE THREAD

**Issue by Penguin98kStudio** [thep0y/python-black#1]
Is there an auto format on save feature ?
Also does it allow to format the current selection ?

**Comment by thep0y** [comment]
- I am considering adding the function of automatic formatting when saving.
- The current selection can be formatted, but there may be some issues.It is recommended to format the entire document.

**Comment by thep0y** [comment]
added https://github.com/thep0y/python-black/commit/7f27e9d05211b5613194b69495d09053092ad194.
