### ISSUE TITLE
Allow View with Python syntax to be formatted

### ISSUE THREAD

**Issue by aerobounce** [thep0y/python-black#11]
Context:
I was playing around with some Python scripts that has no extension and noticed that...

Currently the format command accept `View`s if only filename extension is `.py`:

https://github.com/thep0y/python-black/blob/19166c3b948dd3a4168d77975a96bc5062f5800c/commands.py#L35-L41

Do you mind if it also accepts `View` which Python syntax is set (but not with `.py` extension)?
If that's OK, I'll open PR.

**Comment by thep0y** [comment]
> 

You are welcome to create a pr to solve this issue.
