### ISSUE TITLE
More options for settings

### ISSUE THREAD

**Issue by den4uk** [thep0y/python-black#13]
Nice plugin, very promising and useful.

However, would it be possible to add more parameters to the Sublime settings globally, instead of relying on `pyproject.toml` file being present in the root of the project?

It would be nice to be able to configure it once, and not necessarily as per repository where the toml is located?

It would make sense giving the priority for the pyproject.toml first, then settings.

Many thanks

**Comment by thep0y** [comment]
Have you tried to create a black global configuration file?
https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#where-black-looks-for-the-file

**Comment by den4uk** [comment]
🤦‍♂️ 
Great tip, many thanks!
