### ISSUE TITLE
Allow formatting in untitled files (temporary tabs)

### ISSUE THREAD

**Issue by fievelk** [thep0y/python-black#17]
I often copy-paste snippets of code in new tabs, without saving them as a new file (just to have a look at some data, for example, or to keep notes about small parts of code).
If I try to run python-black when I'm in these tabs I get:
> black: Unrecognized file name

Is it possible to use python-black in untitled tabs?

**Comment by thep0y** [comment]
Even for formatting selections, black needs a file path, and since untitled is not a file, formatting cannot be done.
If my opinion is wrong, you are welcome to create a PR to solve this issue.

**Comment by fievelk** [comment]
Thank you for the quick reply!
I've been using another black plugin before (now unmantained) that allowed formatting untitled files, so I think there might be a way around this issue. 
I can't promise I'll have the availability to work on this, but if I find time I'll give it a try :)

Thanks for working on the package!

**Comment by fievelk** [comment]
First thing that comes to my mind is: the untitled files are still files I guess. They should be temporary files stored somewhere, so finding their path would allow parsing the code.

**Comment by fievelk** [comment]
@thep0y I wrote a PR that allows formatting untitled files (temporary tabs): https://github.com/thep0y/python-black/pull/18
Any feedback is appreciated. I don't have a global overview of the entire project, so if you foresee complications or bugs introduced by the PR, feel free to let me know.

**Comment by thep0y** [comment]
Merged https://github.com/thep0y/python-black/pull/18/commits/1ad9b3c96eb975fc46c297cc8db16691a1a7c5f1
