### ISSUE TITLE
Freshly installed with error

### ISSUE THREAD

**Issue by princemaple** [thep0y/python-black#2]
```
ModuleNotFoundError: No module named 'black'
```

When running the format action

ST4
Win10
I do have black installed globally, but README says it doesn't matter.

**Comment by thep0y** [comment]
I am trying to fix it

**Comment by thep0y** [comment]
It has been fixed, please try to see if an exception occurs after updating to `1.0.2`

**Comment by princemaple** [comment]
Seems to work great now. Thanks.
