### ISSUE TITLE
Support black configs in sublime project settings

### ISSUE THREAD

**Issue by returnchung** [thep0y/python-black#20]
Although there is a `pyproject.toml` config file, however, It will be awesome if the the configs also can be configure in the `sublime-project` settings for project scope.

**Comment by thep0y** [comment]
I'm sure it's not a difficult thing, but it's not a necessary thing either.
I won't add this feature https://github.com/thep0y/python-black/issues/9, but if you can create a PR to add this feature I'll merge it into the project.
