### ISSUE TITLE
Feature: Save without Format

### ISSUE THREAD

**Issue by jaraco** [thep0y/python-black#21]
I love this plugin and really appreciate the Format on Save feature, but sometimes I'm working on a project that doesn't use Black and I'd like to be able to save those files without invoking black. It would be nice if there were a way to suppress the Format on Save for a single invocation, session, or project.

**Comment by thep0y** [comment]
You can turn off automatic formatting in your project by following these steps:
 1. `Project ` > `Save Project As...` > `*/**/<PROJECT>.sublime-project`
 2. Add configuration in `<PROJECT>.sublime-project`:

**Comment by thep0y** [comment]
You can turn off automatic formatting in your project by following these steps:
 1. `Project ` > `Save Project As...` > `*/**/<PROJECT>.sublime-project`
 2. Add configuration in `<PROJECT>.sublime-project`:

**Comment by jaraco** [comment]
That's super-helpful, and I think it's having the desired effect. It's a little annoying that the config has to be in the workspace (and thus SCM clients need to be configured to ignore these files), but this definitely gets 80% of what I wanted.

I wonder if the plugin could be smarter and have an option infer which projects use 'black' for formatting and only reformat files in such projects. Unfortunately, I'm not aware of any config that distinctly identifies that a project uses black. It would likely need to be a fuzzy heuristic that looks at files like .pre-commit and pyproject.toml and requirements* and README for signs that the project uses black. It would probably need to be an opt-in behavior. Maybe `format_on_save` could become `on_save` with values "format", "nothing", "infer" (or "detect").

WDYT?

**Comment by thep0y** [comment]
> ...
> I wonder if the plugin could be smarter and have an option infer which projects use 'black' for formatting and only reformat files in such projects. Unfortunately, I'm not aware of any config that distinctly identifies that a project uses black. It would likely need to be a fuzzy heuristic that looks at files like .pre-commit and pyproject.toml and requirements* and README for signs that the project uses black. It would probably need to be an opt-in behavior. Maybe `format_on_save` could become `on_save` with values "format", "nothing", "infer" (or "detect").
> ...

This is a nice feature, according to the [`black` documentation](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file), it can be determined by `pyproject.toml` whether there is `[tool.black]` section to decide whether to enable automatic formatting.

```js
{
  "format_on_save": false // Turn off automatic formatting.
  "format_on_save": true  // Force auto format on.
  "format_on_save": "smart"  // There is the `[tool.black]` section or not in the `pyproject.toml`.
}
```

By the way, I think there is the `[tool.black]` section or not in the `pyproject.toml` is the only sign to decide whether to use `black` intelligently.

**Comment by jaraco** [comment]
> That's super-helpful, and I think it's having the desired effect.

And today, disabling 'format_on_save' in a local config no longer seems to be having the desired effect.

I've found if I explicitly open `<project>.sublime-project`, it does open a new window and in that window, python-black is disabled, but if I `subl .` to open the project (typically how I open the project), the setting doesn't take. So it seems that adding the configuration is insufficient and one needs to open the project each time. That's rather inconvenient.

**Comment by jaraco** [comment]
> ```js
> {
>   "format_on_save": false // Turn off automatic formatting.
>   "format_on_save": true  // Force auto format on.
>   "format_on_save": "smart"  // There is the `[tool.black]` section or not in the `pyproject.toml`.
> }
> ```

In my experience, I'd avoid accepting two types for the configuration. I typically avoid boolean parameters and try to indicate the effect in the value. That said, I also understand you have backward compatibility concerns, so you may want to simply retain the boolean value. Another choice you could consider is to create a separate config var (e.g. `format_mode: "always" / "smart"` or if you really like the boolean values, `smart_format: true/false`).

In any case, I've stated my preference and I'll be happy to have whatever you settle on.

**Comment by thep0y** [comment]
The config I originally wanted to use was `on, off, smart`, but it conflicts with the previous version's config file.
