### ISSUE TITLE
Black global settings ignored

### ISSUE THREAD

**Issue by schwartzman** [thep0y/python-black#22]
Black global settings are no longer applied.

Have cross-tested with CLI black @ 22.10.0, where global settings are still working as expected.

**Comment by schwartzman** [comment]
Reverting to python-black 1.1.9 is an effective workaround.

**Comment by thep0y** [comment]
Have you been using the 'true' mode?

**Comment by schwartzman** [comment]
Do you mean `"format_on_save": true` in python-black.sublime-settings?

If so, yes.

**Comment by nk9** [comment]
I'm having the same problem. The `line-length` setting is being ignored now. I've had to turn off the plugin for the time being. Here's the relevant portion of `./pyproj.toml`:

```toml
[tool.black]
extend-exclude = "^/migrations/"
line-length = 120
```

**Comment by whyscream** [comment]
Same here, thank you (took some time to receive the update through packagecontrol)
