### ISSUE TITLE
Avoid default context menu

### ISSUE THREAD

**Issue by princemaple** [thep0y/python-black#3]
Maybe a good idea to provide instructions to add context menu instead of adding one by default. Auto save is good enough.

Feel free to ignore and close, though. Just a thought.

**Comment by thep0y** [comment]
Do you mean to delete the default context menu?

**Comment by princemaple** [comment]
Yes, that's what I meant. However, if you prefer having it, feel to ignore me. :)

**Comment by thep0y** [comment]
The reason why I added the context menu is to consider that some people can use the context menu to format code when they don't want to set key binding and do not turn on automatic formatting.
So this context menu is useless for most users. Considering that a small number of users may need it, I do not plan to delete it for the time being.
