### ISSUE TITLE
Incompatible with Apple M1 due to missing arm64 regex library

### ISSUE THREAD

**Issue by PatTheMav** [thep0y/python-black#5]
Thank you for this simple and useful plugin for those that just need to use Black in conjunction with pyright, alas it won't work on M1 Macs as you don't ship an arm64 version of the regex library (which is required by Black iirc).

Would be much appreciated if you could add that library as well.

**Comment by ofen** [comment]
https://github.com/mrabarnett/mrab-regex/issues/432

**Comment by thep0y** [comment]
> Damn that's unfortunate. I had hoped that packagecontrol's own dependency system could help here, but I dunno if it can create wheels on the fly (which - judging by the cffi dependency mentioned as an example doesn't seem to be the case).
> 
> Here's the upstream issue for it, looks like travis is giving trouble into building the correct M1 wheels on CI: https://bitbucket.org/mrabarnett/mrab-regex/issues/399/missing-wheel-for-macosx-and-the-new-m1
> 
> EDIT: In the meantime I simply set up a Python 3.8 environment and used `pip` to install `regex` into that environment - I copied the entire directory from `site-packages` into the Sublime package and it works with that workaround for now.

`regex` now supports M1, but I don’t have an M1 computer. Can you submit a pr?

**Comment by ofen** [comment]
@PatTheMav could you please check this one https://github.com/ofen/python-black/tree/fix-m1-arm64 ?

**Comment by thep0y** [comment]
`1.0.8` has removed the dependency on `regex`, `M1` or higher should work fine.
This issue has been inactive for a long time, please open a new issue if necessary.
