### ISSUE TITLE
How to update black?

### ISSUE THREAD

**Issue by mconigliaro** [thep0y/python-black#6]
I just noticed my editor isn't using the latest version of black. How can I update it?

**Comment by thep0y** [comment]
You need to modify some file codes in https://github.com/thep0y/python-black/tree/main/lib/common to update black and its dependencies.
Or you can wait for me to update it in November or December.

**Comment by mconigliaro** [comment]
Consider this a feature request to allow us to update it ourselves. Maybe with an option to pin to a specific version if we want to?

**Comment by thep0y** [comment]
I don’t have time because I’m busy at work, so I will update black when I have free time in November or December.
You can now update it yourself in the `%SUBLIME_TEXT%/Packages/python-black` directory.

**Comment by thep0y** [comment]
The `black` package used by `python-black` has some modifications, which can be implemented by any user.
The `black` package uses the `click` package and some third-party dependencies. If you want to update `black` yourself, you need to delete the code related to the `click` package and update the third-party dependencies.
This is not a complicated job.
Now I have updated the `black` version to `21.11b1`.
