### ISSUE TITLE
Allow black formatter options in settings

### ISSUE THREAD

**Issue by joshuaimmanuel** [thep0y/python-black#9]
Like how [VSCode](https://code.visualstudio.com/docs/python/editing#_formatterspecific-settings) allows black formatter configuration like `"python.formatting.blackArgs": ["--line-length", "79"]`, it would be great if we allow this option in settings.

Something like:
```json
{
  "format_on_save": true,
  "line_length": 79
}

**Comment by thep0y** [comment]
`python-black` only uses the configuration file of `black`. I don't plan to add any custom configurations in the settings of `python-black`.

**Comment by joshuaimmanuel** [comment]
Thanks for the clarification. I thought adding this settings would ease the development process where we don't have to create the black configuration file in every project.

**Comment by thep0y** [comment]
> Thanks for the clarification. I thought adding this settings would ease the development process where we don't have to create the black configuration file in every project.

You can use global `black` configuration, please refer to the `black` document: https://black.readthedocs.io/en/stable/
